name: Qt6 examples Ubuntu Qt6
on: [push]

jobs:
  Qt6-Examples-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update package info
        run: sudo apt update -y
      - name: Install needed components
        run: sudo apt install -y qmake6 qt6-base-dev cppcheck
      - name: CMake
        run: cmake -B build
      - name: Build
        run: make -C build -j `nproc`
      - name: CPP-Check
        run: make -C build cppcheck
